name: 'ci'

on: [push, pull_request]

jobs:
  build:
    name: 'Build on Node v${{ matrix.node }} ${{ matrix.os.name }} ${{ matrix.arch }}'
    runs-on: ${{ matrix.os.name }}-${{ matrix.os.version }}

    strategy:
      matrix:
        os:
          - name: Ubuntu
            version: latest
          - name: macOS
            version: latest
          - name: Windows
            version: 2019
        arch: [x64]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'
          architecture: ${{ matrix.arch }}

      - name: Install dependencies and build from source
        run: npm ci --build-from-source

      - name: Prebuild binaries
        run: npm run prebuild
